completed prep-javascript-objects
gabriellerramos/prep-0922-code-solutions pull request #10
Opened 2022-09-28 01:12 UTC by gabriellerramos

<img width="634" alt="Screen Shot 2022-09-27 at 9 08 32 PM" src="https://user-images.githubusercontent.com/113288280/192664892-48b702ed-5c62-4f2c-97dd-4ba8dfc69483.png">

2022-09-28 22:24 UTC, thebearingedge requested changes

2022-09-28 22:24 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +var fullName = ' The persons name is: Gabrielle Ramos';
We can construct the person's full name using dot notation to get the `firstName` and `lastName` properties.

```js
var fullName = person.firstName + ' ' + person.lastName;
```

2022-09-28 22:24 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +var previousJob = 'The persons previous job is: sales';
We can add properties to an object by assigning to them

```js
person.job = 'student';
```

2022-10-03 06:07 UTC, gabriellerramos commented
<img width="1305" alt="Screen Shot 2022-10-03 at 2 06 07 AM" src="https://user-images.githubusercontent.com/113288280/193511130-c9a6c4b3-8ac3-44ae-9845-6bd434dfbcb8.png">

2022-10-03 15:13 UTC, thebearingedge approved these changes

2022-10-03 15:14 UTC, merged