Completed exercise
gabriellerramos/prep-0922-code-solutions pull request #11
Opened 2022-09-28 01:33 UTC by gabriellerramos

<img width="559" alt="Screen Shot 2022-09-27 at 9 30 14 PM" src="https://user-images.githubusercontent.com/113288280/192667158-3c5207e4-84fd-413c-aa4a-c3fa891d3ee9.png">

2022-09-28 22:49 UTC, thebearingedge requested changes

2022-09-28 22:49 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +console.log(thirdElement);
We can access elements of an array by their index.

```js
var firstElement = languages[0];
```

2022-09-28 22:49 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +console.log(length);
We can read the length of any array from its `.length` property.

```js
var length = languages.length;
```

2022-09-28 22:49 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +console.log(lastElement);
We can calculate the last index of an array by subtracting 1 from its length and then using the result to access the last element of the array.

```js
var lastElement = languages[languages.length - 1];
```

2022-10-03 06:27 UTC, gabriellerramos commented
<img width="1725" alt="Screen Shot 2022-10-03 at 2 23 35 AM" src="https://user-images.githubusercontent.com/113288280/193513631-b1eb2663-f13b-4ea4-b8e8-f0dce85d9118.png">

2022-10-03 15:14 UTC, thebearingedge approved these changes

2022-10-03 15:15 UTC, merged