completed prep-css-layout-classes example
gabriellerramos/prep-0922-code-solutions pull request #16
Opened 2022-10-03 15:50 UTC by gabriellerramos

https://user-images.githubusercontent.com/113288280/193621485-be2d6983-30af-4d98-ad1c-c083659f900b.mov

2022-10-03 22:42 UTC, thebearingedge requested changes

2022-10-03 22:42 UTC, thebearingedge commented on prep-css-layout-classes/index.html
> +
To get the columns to appear next to each other, we'll want to close them before opening their next sibling.

```html
<div class="container">
  <div class="row">
    <div class="column">
    </div>
    <div class="column">
    </div>
    <div class="column">
    </div>
  </div>
</div>
```

2022-10-05 13:08 UTC, gabriellerramos commented
<img width="1728" alt="Screen Shot 2022-10-05 at 9 06 22 AM" src="https://user-images.githubusercontent.com/113288280/194067849-a6d050db-e63e-480c-a24e-3ac0cce08f37.png">

2022-10-05 16:56 UTC, thebearingedge approved these changes

2022-10-06 00:54 UTC, merged