completed prep-javascript-functions
gabriellerramos/prep-0922-code-solutions pull request #17
Opened 2022-10-03 17:47 UTC by gabriellerramos

<img width="493" alt="Screen Shot 2022-10-03 at 1 45 25 PM" src="https://user-images.githubusercontent.com/113288280/193644315-bc4d9b88-f1b9-4107-87a3-84c0acbcdd92.png">

2022-10-03 22:44 UTC, thebearingedge requested changes

2022-10-03 22:44 UTC, thebearingedge commented on prep-javascript-functions/main.js
> +console.log('greetings:', greeting);
We can concatenate the string `'Hello '` before the `name` parameter to get a greeting for any name.

```js
function getGreeting(name) {
  var result = 'Hello ' + name + '!';
  return result;
}

var greeting = getGreeting('Gabrielle');
console.log('greetings:', greeting);
```

2022-10-05 12:57 UTC, gabriellerramos commented
<img width="511" alt="Screen Shot 2022-10-05 at 8 54 48 AM" src="https://user-images.githubusercontent.com/113288280/194065808-be872442-9d37-4dca-b872-49e16530640c.png">

2022-10-05 16:58 UTC, thebearingedge approved these changes

2022-10-06 00:54 UTC, merged