Completed prep-html-links exercise
gabriellerramos/prep-0922-code-solutions pull request #5
Opened 2022-09-18 21:12 UTC by gabriellerramos

https://user-images.githubusercontent.com/113288280/190928322-6e36d913-a509-4588-9b5b-782c6b7c3bb9.mov

2022-09-18 23:21 UTC, thebearingedge requested changes

2022-09-18 23:21 UTC, thebearingedge commented on prep-html-links/contact-us/contact-us.html
> +  <link href="prep-html-link/index" rel="contact-us/index">
Hi Gabrielle, be sure to put the visible content of your page into a `body` element and the `head` and `body` both belong in an `html` element, as outlined in the `prep-html-skeleton` exercise.

2022-09-20 23:44 UTC, gabriellerramos commented
<img width="1728" alt="Screen Shot 2022-09-20 at 7 43 18 PM" src="https://user-images.githubusercontent.com/113288280/191383841-d69174ae-db90-414e-8342-049eabdb55c2.png">

2022-09-21 00:35 UTC, thebearingedge requested changes

2022-09-21 00:35 UTC, thebearingedge commented on prep-html-links/contact-us/contact-us.html
> +</body>
Clicking this link should go to the home page, so you'll need to change your `href` value to `"../index.html"`

2022-09-21 00:35 UTC, thebearingedge commented on prep-html-links/index.html
> +  <a href="contact-us"> Click here to go to the contact page </a>
Clicking this link should go to the `contact-us.html` file inside of the `contact-us` folder, so you'll need to change your `href` value to `"contact-us/contact-us.html"`

2022-09-21 01:52 UTC, gabriellerramos commented
<img width="1728" alt="Screen Shot 2022-09-20 at 7 43 18 PM" src="https://user-images.githubusercontent.com/113288280/191396439-e6fe4eb4-94a2-4977-ac5d-e7f25a390ef3.png">

2022-09-21 22:56 UTC, thebearingedge requested changes

2022-09-21 22:56 UTC, thebearingedge commented on prep-html-links/contact-us/contact-us.html
> +</body>
This one will also need to get changed ☝️

2022-10-03 15:02 UTC, thebearingedge requested changes

2022-10-03 15:02 UTC, thebearingedge commented on prep-html-links/index.html
> +  <a href="contact-us/index.html"> Click here to go to the contact page </a>
Unfortunately, this link won't work because there is no `index.html` in the `contact-us` directory.

2022-10-05 13:45 UTC, gabriellerramos commented
<img width="918" alt="Screen Shot 2022-10-05 at 9 44 18 AM" src="https://user-images.githubusercontent.com/113288280/194075917-dd75ede6-93e4-4e15-8d67-3d56e1a3b7fc.png">

2022-10-05 16:53 UTC, thebearingedge approved these changes

2022-10-06 00:55 UTC, merged