completed prep-css-display exercise
gabriellerramos/prep-0922-code-solutions pull request #8
Opened 2022-09-21 20:43 UTC by gabriellerramos

<img width="1728" alt="Screen Shot 2022-09-21 at 4 40 53 PM" src="https://user-images.githubusercontent.com/113288280/191606646-4a9e2c17-3c6a-4f86-875b-e95249bb96f6.png">

2022-09-22 00:10 UTC, thebearingedge requested changes

2022-09-22 00:10 UTC, thebearingedge commented on prep-css-display/index.html
> +}
Hi Gabrielle, for this exercise, we want to write all of our CSS code inside one <style> element in the <head> of the document.

2022-09-27 22:05 UTC, gabriellerramos commented
<img width="873" alt="Screen Shot 2022-09-27 at 6 04 41 PM" src="https://user-images.githubusercontent.com/113288280/192646048-988a9744-2c87-4a08-9ae3-c52b4fad6298.png">

2022-09-28 00:15 UTC, thebearingedge requested changes
Hi Gabrielle, we'll want to make sure that our HTML document has all of the necessary parts to be valid. The style can go inside the `<head>` below the `<title>`

```html
<!doctype html>
<html>
<head>
  <title>CSS Display Properties</title>
  <style>
    /* CSS code goes here */
  </style>
</head>
<body>
  <!-- visible HTML content goes here -->
</body>
</html
```

2022-10-03 05:06 UTC, gabriellerramos commented
<img width="780" alt="Screen Shot 2022-10-03 at 1 04 19 AM" src="https://user-images.githubusercontent.com/113288280/193505165-09e5296f-2d9e-45b3-ab88-d05e4ee8013d.png">

2022-10-03 15:07 UTC, thebearingedge requested changes

2022-10-03 15:07 UTC, thebearingedge commented on prep-css-display/index.html
> +</head>
The closing tag for the head element should go after the closing tag for the style element.

2022-10-03 15:07 UTC, thebearingedge commented on prep-css-display/index.html
> +      <div> I am a div and by default I am block, which means I take up all the space I can horizontally.</div>
The div and ul elements should all go in the body of the document, you can see an example here

https://github.com/gabriellerramos/prep-0922-code-solutions/pull/8#pullrequestreview-1122856949

2022-10-05 13:40 UTC, gabriellerramos commented
<img width="1718" alt="Screen Shot 2022-10-05 at 9 40 06 AM" src="https://user-images.githubusercontent.com/113288280/194074750-50a52a6a-ee05-4b77-9f8d-705e110d11da.png">

2022-10-05 16:54 UTC, thebearingedge approved these changes

2022-10-06 00:55 UTC, merged