Completed prep example
gabriellerramos/prep-0922-code-solutions pull request #9
Opened 2022-09-28 00:31 UTC by gabriellerramos

<img width="631" alt="Screen Shot 2022-09-27 at 8 29 39 PM" src="https://user-images.githubusercontent.com/113288280/192661012-34de3bf5-0b0d-47a2-b041-91bb579103ec.png">

2022-09-28 22:21 UTC, thebearingedge requested changes

2022-09-28 22:21 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +var nothing = 'null';
We'll want to leave out the quotes for numbers, booleans, and `null` so that the JavaScript engine doesn't interpret them as strings.

2022-09-28 22:21 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +console.log(never);
We can declare a variable without assigning it any value.

```js
var never;
```

2022-10-03 05:21 UTC, gabriellerramos commented
<img width="1563" alt="Screen Shot 2022-10-03 at 1 18 45 AM" src="https://user-images.githubusercontent.com/113288280/193506486-66d3b8a5-ef6c-4362-b06a-e8f56d02bc54.png">

2022-10-03 15:12 UTC, thebearingedge approved these changes

2022-10-03 15:14 UTC, merged